package com.sureti.models

import com.google.gson.annotations.SerializedName

data class ActiveCheckModel(
    @SerializedName("id") var id: String,
    @SerializedName("checkNo") var checkNo: String,
    @SerializedName("checkAmount") var checkAmount: Int,
    @SerializedName("approximatePrincipalLoanBalance") var approximatePrincipalLoanBalance: Int,
    @SerializedName("claimNo") var claimNo: String,
    @SerializedName("mortgagecompanypartner") var mortgagecompanypartner: String,
    @SerializedName("mortgageId") var mortgageId: String,
    @SerializedName("generateduniqueid") var generateduniqueid: String,
    @SerializedName("postMitigationScanLongLat") var postMitigationScanLongLat: String,
    @SerializedName("progressScanLongLat") var progressScanLongLat: String,
    @SerializedName("postRepairScanLongLat") var postRepairScanLongLat: String,
    @SerializedName("activeOrClosed") var activeOrClosed: String,
    @SerializedName("preferredcontractor") var preferredcontractor: String,
    @SerializedName("lossSnapshot") var lossSnapshot: String,
    @SerializedName("jobidforbranch") var jobidforbranch: String,
    @SerializedName("insurancecompanyname") var insurancecompanyname: String,
    @SerializedName("relatedDocuments") var relatedDocuments: List<String>,
    @SerializedName("approvedScopes") var approvedScopes: List<String>,
    @SerializedName("payments") var payments: List<String>,
    @SerializedName("proposals") var proposals: List<String>,
    @SerializedName("checkFrontImageURL") var checkFrontImageURL: String,
    @SerializedName("checkBackImageURL") var checkBackImageURL: String,
    @SerializedName("checkStatus") var checkStatus: String,
    @SerializedName("phdocument1status") var phdocument1status: String,
    @SerializedName("phdocument2status") var phdocument2status: String,
    @SerializedName("contractordocument1status") var contractordocument1status: String,
    @SerializedName("contractproposalcombinedstatus") var contractproposalcombinedstatus: String,
    @SerializedName("approvedscopescombinedstatus") var approvedscopescombinedstatus: String,
    @SerializedName("postMitigationScanURLStatus") var postMitigationScanURLStatus: String,
    @SerializedName("postRepairScanURLStatus") var postRepairScanURLStatus: String,
    @SerializedName("progressScanURLStatus") var progressScanURLStatus: String,
    @SerializedName("postMitigationScanURL") var postMitigationScanURL: String,
    @SerializedName("postRepairScanURL") var postRepairScanURL: String,
    @SerializedName("progressScanURL") var progressScanURL: String,
    @SerializedName("noOfComments") var noOfComments: Int,
    @SerializedName("noOfUnreadComments") var noOfUnreadComments: Int,
    @SerializedName("addressofloss") var addressofloss: String,
    @SerializedName("loannumber") var loannumber: String,
    @SerializedName("addressoflossLongitude") var addressoflossLongitude: Double,
    @SerializedName("addressoflossLatitude") var addressoflossLatitude: Double,
    @SerializedName("streetandapartmentno") var streetandapartmentno: String,
    @SerializedName("collabortator") var collabortator: List<CollaboratorModel>,
    @SerializedName("branchcollabortator") var branchcollabortator: List<BranchCollaboratorModel>,
    @SerializedName("laneId") var laneId: String,
    @SerializedName("branch") var branch: BranchModel,
    @SerializedName("amountalreadypaid") var amountalreadypaid: Int,
    @SerializedName("userInfo") var userInfo: UserInfoModel
)
