package com.sureti.models

import com.google.gson.annotations.SerializedName

data class BranchModel(
    @SerializedName("id") var id: String,
    @SerializedName("email") var email: String,
    @SerializedName("company") var company: String,
    @SerializedName("branchname") var branchname: String,
    @SerializedName("firstname") var firstname: String,
    @SerializedName("lastname") var lastname: String,
    @SerializedName("branchaddress") var branchaddress: String,
    @SerializedName("branchaddresslong") var branchaddresslong: Double,
    @SerializedName("branchaddresslat") var branchaddresslat: Double,
    @SerializedName("aptste") var aptste: String,
    @SerializedName("certified") var certified: Boolean,
    @SerializedName("profilepicturestatus") var profilepicturestatus: String,
    @SerializedName("suretiSCORE") var suretiSCORE: Int,
    @SerializedName("processingfees") var processingfees: Int,
    @SerializedName("profilepicture") var profilepicture: String,
    @SerializedName("dunandbradnumber") var dunandbradnumber: String,
    @SerializedName("subscriptionstatus") var subscriptionstatus: String,
    @SerializedName("subscriptionstartdate") var subscriptionstartdate: String,
    @SerializedName("subscriptionnextdate") var subscriptionnextdate: String,
    @SerializedName("aimc") var aimc: String,
    @SerializedName("aimcfilename") var aimcfilename: String,
    @SerializedName("aimcstatus") var aimcstatus: String,
    @SerializedName("aimcexpirydate") var aimcexpirydate: String,
    @SerializedName("license") var license: String,
    @SerializedName("licensefilename") var licensefilename: String,
    @SerializedName("licenseStatus") var licenseStatus: String,
    @SerializedName("licenseexpirydate") var licenseexpirydate: String,
    @SerializedName("w9") var w9: String,
    @SerializedName("w9filename") var w9filename: String,
    @SerializedName("w9status") var w9status: String,
    @SerializedName("w9expirydate") var w9expirydate: String,
    @SerializedName("certifcateofliability") var certifcateofliability: String,
    @SerializedName("certifcateofliabilityfilename") var certifcateofliabilityfilename: String,
    @SerializedName("certifcateofliabilitystatus") var certifcateofliabilitystatus: String,
    @SerializedName("certifcateofliabilityexpirydate") var certifcateofliabilityexpirydate: String,
    @SerializedName("suretybond") var suretybond: String,
    @SerializedName("suretybondfilename") var suretybondfilename: String,
    @SerializedName("suretybondstatus") var suretybondstatus: String,
    @SerializedName("suretybondexpirydate") var suretybondexpirydate: String,
    @SerializedName("phonenumber") var phonenumber: String,
    @SerializedName("emailverified") var emailverified: String,
    @SerializedName("profilecompletion") var profilecompletion: Int,
    @SerializedName("branchstatus") var branchstatus: String,
    @SerializedName("totalcheckvolume") var totalcheckvolume: Int,
    @SerializedName("totalinsuranceproceeds") var totalinsuranceproceeds: Int,
    @SerializedName("createdAt") var createdAt: String,
    @SerializedName("subscriptionneverbought") var subscriptionneverbought: Boolean,
    @SerializedName("website") var website: String,
    @SerializedName("description") var description: String,
    @SerializedName("showDemoButton") var showDemoButton: Boolean,
    @SerializedName("nextcharge") var nextcharge: String
)
